### ISSUE TITLE
[ci] fix frontend error in CI

### ISSUE THREAD

**Issue by hsluoyz** [casbin/casnode#1]
The frontend starts to fail after updating to Antd 5 and React 18: https://github.com/casbin/casnode/actions/runs/5835799860/job/15828074562

Need a fix

![image](https://github.com/casbin/casnode/assets/3787410/fb5a7e79-07c9-4492-ac30-e20f044db6ee)

**Comment by hsluoyz** [comment]
@yehong-z

**Comment by hejianbo1994** [comment]
麻烦快点解决吧
