### ISSUE TITLE
npm ERR! ,Help

### ISSUE THREAD

**Issue by truman1998** [casbin/casnode#552]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @craco/craco@6.4.5
npm ERR! Found: react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"5.0.1" from the root project
npm ERR!   peer react-scripts@"^5.0.0" from craco-less@2.0.0
npm ERR!   node_modules/craco-less
npm ERR!     craco-less@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^6.4.5" from the root project
npm ERR!   peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!   node_modules/craco-less
npm ERR!     craco-less@"^2.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-scripts@4.0.3
npm ERR! node_modules/react-scripts
npm ERR!   peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR!   node_modules/@craco/craco
npm ERR!     @craco/craco@"^6.4.5" from the root project
npm ERR!     peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!     node_modules/craco-less
npm ERR!       craco-less@"^2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-17T12_42_28_038Z-debug-0.log

[root@web _logs]# npm -v
8.19.2

[Uploading 2022-10-17T12_42_28_038Z-debug-0.log…]()

**Comment by truman1998** [comment]
npm install –legacy-peer-deps


npm ERR! code 1
npm ERR! path /root/casdoor/web
npm ERR! command failed
npm ERR! command sh -c -- node -e "if (process.env.npm_execpath.indexOf('yarn') === -1) throw new Error('Use yarn for installing: https://yarnpkg.com/en/docs/install')"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-17T13_02_36_095Z-debug-0.log

**Comment by hsluoyz** [comment]
@truman1998 see: `Use yarn for installing: https://yarnpkg.com/en/docs/install'`, use Yarn instead of NPM

**Comment by truman1998** [comment]
[root@web web]# npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @craco/craco@6.4.5
npm ERR! Found: react-scripts@5.0.1
npm ERR! node_modules/react-scripts
npm ERR!   react-scripts@"5.0.1" from the root project
npm ERR!   peer react-scripts@"^5.0.0" from craco-less@2.0.0
npm ERR!   node_modules/craco-less
npm ERR!     craco-less@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^6.4.5" from the root project
npm ERR!   peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!   node_modules/craco-less
npm ERR!     craco-less@"^2.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-scripts@4.0.3
npm ERR! node_modules/react-scripts
npm ERR!   peer react-scripts@"^4.0.0" from @craco/craco@6.4.5
npm ERR!   node_modules/@craco/craco
npm ERR!     @craco/craco@"^6.4.5" from the root project
npm ERR!     peer @craco/craco@"^6.0.0" from craco-less@2.0.0
npm ERR!     node_modules/craco-less
npm ERR!       craco-less@"^2.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-17T14_24_54_182Z-debug-0.log

**Comment by truman1998** [comment]
[root@web ~]# npm install --legacy-peer-deps
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /root/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-17T14_27_12_101Z-debug-0.log

**Comment by truman1998** [comment]
**Use the command successfully...npm i vant@latest-v2 -S -force**

added 29 packages, removed 17 packages, changed 2 packages, and audited 1962 packages in 26s

243 packages are looking for funding
  run `npm fund` for details

8 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**continue**
[root@web web]# npm run build

> web@0.1.0 build
> craco build
Creating an optimized production build...
<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb06730 node::Abort() [node]
 2: 0xa1b6d0  [node]
 3: 0xce1dd0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xce2177 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xe997e5  [node]
 6: 0xea94ad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xeac1ae v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xe6d6ea v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x11e6456 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x15da0d9  [node]


Failed to access http://your-ip:8000
Prompt 500 Internal Privoxy Error

[root@web casdoor]# sudo nohup ./main &
[1] 8460
[root@web casdoor]# nohup: ignore input and append output to "nohup.out"
