### ISSUE TITLE
Failed to access http://your-ip:8000

### ISSUE THREAD

**Issue by truman1998** [casbin/casnode#554]
`[root@web web]# npm run build

> web@0.1.0 build
> craco build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  783.97 kB  build/static/js/main.2df5edba.js
  73.89 kB   build/static/css/main.f8e90a0a.css

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment`

`[root@web web]# cd ..
[root@web casdoor]# sudo nohup ./main &
[1] 27548
[root@web casdoor]# nohup: ignore input and append output to "nohup.out"`

**Unable to access http://your-ip:8000 to configure Casnode**

`[root@web web]# netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN     
tcp6       0      0 :::111                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::8888                 :::*                    LISTEN   `

**to open ports 7001 and 8000, but it does not show occupied**

The database password has been changed to 123
driverName = mysql
dataSourceName = root:123@tcp(localhost:3306)/

**Comment by hsluoyz** [comment]
@truman1998 use Docker to deploy, it's much easier: https://casnode.org/docs/docker
