### ISSUE TITLE
The casdoor page is blank

### ISSUE THREAD

**Issue by truman1998** [casbin/casnode#555]
[root@web web]# serve -s build -l 8000
ERROR: Cannot copy server address to clipboard: Couldn't find the `xsel` binary and fallback didn't work. On Debian/Ubuntu you can install xsel with: sudo apt install xsel.

   ┌──────────────────────────────────────────────────┐
   │                                                  │
   │   Serving!                                       │
   │                                                  │
   │   - Local:            http://localhost:8000      │
   │   - On Your Network:  http://165.22.14.90:8000   │
   │                                                  │
   └──────────────────────────────────────────────────┘

![image](https://user-images.githubusercontent.com/68187484/196463804-f06993d9-372c-4792-b38f-d73f12553ed0.png)

**Comment by hsluoyz** [comment]
Not related to Casnode
